import 'package:flutter/material.dart';
import 'package:islame/core/Theme/color_palette.dart';
import 'package:islame/core/constants/app_assets.dart';
import 'package:islame/layout/pages/quran/widgets/quran_card_widget.dart';
import 'package:islame/layout/pages/quran/widgets/recentlyCardWidget.dart';
import 'package:islame/models/sura_data_model.dart';


class QyranView extends StatefulWidget {
  const QyranView({super.key});

  @override
  State<QyranView> createState() => _QuranViewState();
}

class _QuranViewState extends State<QyranView> {
  List<SuraDataModel> allQuranSures = [
    SuraDataModel(suraNameEN: "Al-Fatiha",
        suraNameAR: "الفاتحة",
        suraNumber: 1,
        suraAyahCount: 7),
    SuraDataModel(suraNameEN: "Al-Baqarah",
        suraNameAR: "البقرة",
        suraNumber: 2,
        suraAyahCount: 286),
    SuraDataModel(suraNameEN: "Aal-E-Imran",
        suraNameAR: "آل عمران",
        suraNumber: 3,
        suraAyahCount: 200),
    SuraDataModel(suraNameEN: "An-Nisa'",
        suraNameAR: "النساء",
        suraNumber: 4,
        suraAyahCount: 176),
    SuraDataModel(suraNameEN: "Al-Ma'idah",
        suraNameAR: "المائدة",
        suraNumber: 5,
        suraAyahCount: 120),
    SuraDataModel(suraNameEN: "Al-An'am",
        suraNameAR: "الأنعام",
        suraNumber: 6,
        suraAyahCount: 165),
    SuraDataModel(suraNameEN: "Al-A'raf",
        suraNameAR: "الأعراف",
        suraNumber: 7,
        suraAyahCount: 206),
    SuraDataModel(suraNameEN: "Al-Anfal",
        suraNameAR: "الأنفال",
        suraNumber: 8,
        suraAyahCount: 75),
    SuraDataModel(suraNameEN: "At-Tawbah",
        suraNameAR: "التوبة",
        suraNumber: 9,
        suraAyahCount: 129),
    SuraDataModel(suraNameEN: "Yunus",
        suraNameAR: "يونس",
        suraNumber: 10,
        suraAyahCount: 109),
    SuraDataModel(suraNameEN: "Hud",
        suraNameAR: "هود",
        suraNumber: 11,
        suraAyahCount: 123),
    SuraDataModel(suraNameEN: "Yusuf",
        suraNameAR: "يوسف",
        suraNumber: 12,
        suraAyahCount: 111),
    SuraDataModel(suraNameEN: "Ar-Ra'd",
        suraNameAR: "الرعد",
        suraNumber: 13,
        suraAyahCount: 43),
    SuraDataModel(suraNameEN: "Ibrahim",
        suraNameAR: "إبراهيم",
        suraNumber: 14,
        suraAyahCount: 52),
    SuraDataModel(suraNameEN: "Al-Hijr",
        suraNameAR: "الحجر",
        suraNumber: 15,
        suraAyahCount: 99),
    SuraDataModel(suraNameEN: "An-Nahl",
        suraNameAR: "النحل",
        suraNumber: 16,
        suraAyahCount: 128),
    SuraDataModel(suraNameEN: "Al-Isra",
        suraNameAR: "الإسراء",
        suraNumber: 17,
        suraAyahCount: 111),
    SuraDataModel(suraNameEN: "Al-Kahf",
        suraNameAR: "الكهف",
        suraNumber: 18,
        suraAyahCount: 110),
    SuraDataModel(suraNameEN: "Maryam",
        suraNameAR: "مريم",
        suraNumber: 19,
        suraAyahCount: 98),
    SuraDataModel(suraNameEN: "Ta-Ha",
        suraNameAR: "طه",
        suraNumber: 20,
        suraAyahCount: 135),
    SuraDataModel(suraNameEN: "Al-Anbiya",
        suraNameAR: "الأنبياء",
        suraNumber: 21,
        suraAyahCount: 112),
    SuraDataModel(suraNameEN: "Al-Hajj",
        suraNameAR: "الحج",
        suraNumber: 22,
        suraAyahCount: 78),
    SuraDataModel(suraNameEN: "Al-Mu'minun",
        suraNameAR: "المؤمنون",
        suraNumber: 23,
        suraAyahCount: 118),
    SuraDataModel(suraNameEN: "An-Nur",
        suraNameAR: "النور",
        suraNumber: 24,
        suraAyahCount: 64),
    SuraDataModel(suraNameEN: "Al-Furqan",
        suraNameAR: "الفرقان",
        suraNumber: 25,
        suraAyahCount: 77),
    SuraDataModel(suraNameEN: "Ash-Shu'ara",
        suraNameAR: "الشعراء",
        suraNumber: 26,
        suraAyahCount: 227),
    SuraDataModel(suraNameEN: "An-Naml",
        suraNameAR: "النمل",
        suraNumber: 27,
        suraAyahCount: 93),
    SuraDataModel(suraNameEN: "Al-Qasas",
        suraNameAR: "القصص",
        suraNumber: 28,
        suraAyahCount: 88),
    SuraDataModel(suraNameEN: "Al-Ankabut",
        suraNameAR: "العنكبوت",
        suraNumber: 29,
        suraAyahCount: 69),
    SuraDataModel(suraNameEN: "Ar-Rum",
        suraNameAR: "الروم",
        suraNumber: 30,
        suraAyahCount: 60),
    SuraDataModel(suraNameEN: "Luqman",
        suraNameAR: "لقمان",
        suraNumber: 31,
        suraAyahCount: 34),
    SuraDataModel(suraNameEN: "As-Sajda",
        suraNameAR: "السجدة",
        suraNumber: 32,
        suraAyahCount: 30),
    SuraDataModel(suraNameEN: "Al-Ahzab",
        suraNameAR: "الأحزاب",
        suraNumber: 33,
        suraAyahCount: 73),
    SuraDataModel(suraNameEN: "Saba",
        suraNameAR: "سبأ",
        suraNumber: 34,
        suraAyahCount: 54),
    SuraDataModel(suraNameEN: "Fatir",
        suraNameAR: "فاطر",
        suraNumber: 35,
        suraAyahCount: 45),
    SuraDataModel(suraNameEN: "Ya-Sin",
        suraNameAR: "يس",
        suraNumber: 36,
        suraAyahCount: 83),
    SuraDataModel(suraNameEN: "As-Saffat",
        suraNameAR: "الصافات",
        suraNumber: 37,
        suraAyahCount: 182),
    SuraDataModel(
        suraNameEN: "Sad", suraNameAR: "ص", suraNumber: 38, suraAyahCount: 88),
    SuraDataModel(suraNameEN: "Az-Zumar",
        suraNameAR: "الزمر",
        suraNumber: 39,
        suraAyahCount: 75),
    SuraDataModel(suraNameEN: "Ghafir",
        suraNameAR: "غافر",
        suraNumber: 40,
        suraAyahCount: 85),
    SuraDataModel(suraNameEN: "Fussilat",
        suraNameAR: "فصلت",
        suraNumber: 41,
        suraAyahCount: 54),
    SuraDataModel(suraNameEN: "Ash-Shura",
        suraNameAR: "الشورى",
        suraNumber: 42,
        suraAyahCount: 53),
    SuraDataModel(suraNameEN: "Az-Zukhruf",
        suraNameAR: "الزخرف",
        suraNumber: 43,
        suraAyahCount: 89),
    SuraDataModel(suraNameEN: "Ad-Dukhan",
        suraNameAR: "الدخان",
        suraNumber: 44,
        suraAyahCount: 59),
    SuraDataModel(suraNameEN: "Al-Jathiya",
        suraNameAR: "الجاثية",
        suraNumber: 45,
        suraAyahCount: 37),
    SuraDataModel(suraNameEN: "Al-Ahqaf",
        suraNameAR: "الأحقاف",
        suraNumber: 46,
        suraAyahCount: 35),
    SuraDataModel(suraNameEN: "Muhammad",
        suraNameAR: "محمد",
        suraNumber: 47,
        suraAyahCount: 38),
    SuraDataModel(suraNameEN: "Al-Fath",
        suraNameAR: "الفتح",
        suraNumber: 48,
        suraAyahCount: 29),
    SuraDataModel(suraNameEN: "Al-Hujurat",
        suraNameAR: "الحجرات",
        suraNumber: 49,
        suraAyahCount: 18),
    SuraDataModel(
        suraNameEN: "Qaf", suraNameAR: "ق", suraNumber: 50, suraAyahCount: 45),
    SuraDataModel(suraNameEN: "Adh-Dhariyat",
        suraNameAR: "الذاريات",
        suraNumber: 51,
        suraAyahCount: 60),
    SuraDataModel(suraNameEN: "At-Tur",
        suraNameAR: "الطور",
        suraNumber: 52,
        suraAyahCount: 49),
    SuraDataModel(suraNameEN: "An-Najm",
        suraNameAR: "النجم",
        suraNumber: 53,
        suraAyahCount: 62),
    SuraDataModel(suraNameEN: "Al-Qamar",
        suraNameAR: "القمر",
        suraNumber: 54,
        suraAyahCount: 55),
    SuraDataModel(suraNameEN: "Ar-Rahman",
        suraNameAR: "الرحمن",
        suraNumber: 55,
        suraAyahCount: 78),
    SuraDataModel(suraNameEN: "Al-Waqi'a",
        suraNameAR: "الواقعة",
        suraNumber: 56,
        suraAyahCount: 96),
    SuraDataModel(suraNameEN: "Al-Hadid",
        suraNameAR: "الحديد",
        suraNumber: 57,
        suraAyahCount: 29),
    SuraDataModel(suraNameEN: "Al-Mujadila",
        suraNameAR: "المجادلة",
        suraNumber: 58,
        suraAyahCount: 22),
    SuraDataModel(suraNameEN: "Al-Hashr",
        suraNameAR: "الحشر",
        suraNumber: 59,
        suraAyahCount: 24),
    SuraDataModel(suraNameEN: "Al-Mumtahina",
        suraNameAR: "الممتحنة",
        suraNumber: 60,
        suraAyahCount: 13),
    SuraDataModel(suraNameEN: "As-Saff",
        suraNameAR: "الصف",
        suraNumber: 61,
        suraAyahCount: 14),
    SuraDataModel(suraNameEN: "Al-Jumu'a",
        suraNameAR: "الجمعة",
        suraNumber: 62,
        suraAyahCount: 11),
    SuraDataModel(suraNameEN: "Al-Munafiqun",
        suraNameAR: "المنافقون",
        suraNumber: 63,
        suraAyahCount: 11),
    SuraDataModel(suraNameEN: "At-Taghabun",
        suraNameAR: "التغابن",
        suraNumber: 64,
        suraAyahCount: 18),
    SuraDataModel(suraNameEN: "At-Talaq",
        suraNameAR: "الطلاق",
        suraNumber: 65,
        suraAyahCount: 12),
    SuraDataModel(suraNameEN: "At-Tahrim",
        suraNameAR: "التحريم",
        suraNumber: 66,
        suraAyahCount: 12),
    SuraDataModel(suraNameEN: "Al-Mulk",
        suraNameAR: "الملك",
        suraNumber: 67,
        suraAyahCount: 30),
    SuraDataModel(suraNameEN: "Al-Qalam",
        suraNameAR: "القلم",
        suraNumber: 68,
        suraAyahCount: 52),
    SuraDataModel(suraNameEN: "Al-Haqqah",
        suraNameAR: "الحاقة",
        suraNumber: 69,
        suraAyahCount: 52),
    SuraDataModel(suraNameEN: "Al-Ma'arij",
        suraNameAR: "المعارج",
        suraNumber: 70,
        suraAyahCount: 44),
    SuraDataModel(suraNameEN: "Nuh",
        suraNameAR: "نوح",
        suraNumber: 71,
        suraAyahCount: 28),
    SuraDataModel(suraNameEN: "Al-Jinn",
        suraNameAR: "الجن",
        suraNumber: 72,
        suraAyahCount: 28),
    SuraDataModel(suraNameEN: "Al-Muzzammil",
        suraNameAR: "المزمل",
        suraNumber: 73,
        suraAyahCount: 20),
    SuraDataModel(suraNameEN: "Al-Muddathir",
        suraNameAR: "المدثر",
        suraNumber: 74,
        suraAyahCount: 56),
    SuraDataModel(suraNameEN: "Al-Qiyamah",
        suraNameAR: "القيامة",
        suraNumber: 75,
        suraAyahCount: 40),
    SuraDataModel(suraNameEN: "Al-Insan",
        suraNameAR: "الإنسان",
        suraNumber: 76,
        suraAyahCount: 31),
    SuraDataModel(suraNameEN: "Al-Mursalat",
        suraNameAR: "المرسلات",
        suraNumber: 77,
        suraAyahCount: 50),
    SuraDataModel(suraNameEN: "An-Naba'",
        suraNameAR: "النبأ",
        suraNumber: 78,
        suraAyahCount: 40),
    SuraDataModel(suraNameEN: "An-Nazi'at",
        suraNameAR: "النازعات",
        suraNumber: 79,
        suraAyahCount: 46),
    SuraDataModel(suraNameEN: "Abasa",
        suraNameAR: "عبس",
        suraNumber: 80,
        suraAyahCount: 42),
    SuraDataModel(suraNameEN: "At-Takwir",
        suraNameAR: "التكوير",
        suraNumber: 81,
        suraAyahCount: 29),
    SuraDataModel(suraNameEN: "Al-Infitar",
        suraNameAR: "الانفطار",
        suraNumber: 82,
        suraAyahCount: 19),
    SuraDataModel(suraNameEN: "Al-Mutaffifin",
        suraNameAR: "المطففين",
        suraNumber: 83,
        suraAyahCount: 36),
    SuraDataModel(suraNameEN: "Al-Inshiqaq",
        suraNameAR: "الانشقاق",
        suraNumber: 84,
        suraAyahCount: 25),
    SuraDataModel(suraNameEN: "Al-Buruj",
        suraNameAR: "البروج",
        suraNumber: 85,
        suraAyahCount: 22),
    SuraDataModel(suraNameEN: "At-Tariq",
        suraNameAR: "الطارق",
        suraNumber: 86,
        suraAyahCount: 17),
    SuraDataModel(suraNameEN: "Al-A'la",
        suraNameAR: "الأعلى",
        suraNumber: 87,
        suraAyahCount: 19),
    SuraDataModel(suraNameEN: "Al-Ghashiyah",
        suraNameAR: "الغاشية",
        suraNumber: 88,
        suraAyahCount: 26),
    SuraDataModel(suraNameEN: "Al-Fajr",
        suraNameAR: "الفجر",
        suraNumber: 89,
        suraAyahCount: 30),
    SuraDataModel(suraNameEN: "Al-Balad",
        suraNameAR: "البلد",
        suraNumber: 90,
        suraAyahCount: 20),
    SuraDataModel(suraNameEN: "Ash-Shams",
        suraNameAR: "الشمس",
        suraNumber: 91,
        suraAyahCount: 15),
    SuraDataModel(suraNameEN: "Al-Lail",
        suraNameAR: "الليل",
        suraNumber: 92,
        suraAyahCount: 21),
    SuraDataModel(suraNameEN: "Ad-Duha",
        suraNameAR: "الضحى",
        suraNumber: 93,
        suraAyahCount: 11),
    SuraDataModel(suraNameEN: "Ash-Sharh",
        suraNameAR: "الشرح",
        suraNumber: 94,
        suraAyahCount: 8),
    SuraDataModel(suraNameEN: "At-Tin",
        suraNameAR: "التين",
        suraNumber: 95,
        suraAyahCount: 8),
    SuraDataModel(suraNameEN: "Al-Alaq",
        suraNameAR: "العلق",
        suraNumber: 96,
        suraAyahCount: 19),
    SuraDataModel(suraNameEN: "Al-Qadr",
        suraNameAR: "القدر",
        suraNumber: 97,
        suraAyahCount: 5),
    SuraDataModel(suraNameEN: "Al-Bayyina",
        suraNameAR: "البينة",
        suraNumber: 98,
        suraAyahCount: 8),
    SuraDataModel(suraNameEN: "Az-Zalzala",
        suraNameAR: "الزلزلة",
        suraNumber: 99,
        suraAyahCount: 8),
    SuraDataModel(suraNameEN: "Al-Adiyat",
        suraNameAR: "العاديات",
        suraNumber: 100,
        suraAyahCount: 11),
    SuraDataModel(suraNameEN: "Al-Qari'a",
        suraNameAR: "القارعة",
        suraNumber: 101,
        suraAyahCount: 11),
    SuraDataModel(suraNameEN: "At-Takathur",
        suraNameAR: "التكاثر",
        suraNumber: 102,
        suraAyahCount: 8),
    SuraDataModel(suraNameEN: "Al-Asr",
        suraNameAR: "العصر",
        suraNumber: 103,
        suraAyahCount: 3),
    SuraDataModel(suraNameEN: "Al-Humazah",
        suraNameAR: "الهمزة",
        suraNumber: 104,
        suraAyahCount: 9),
    SuraDataModel(suraNameEN: "Al-Fil",
        suraNameAR: "الفيل",
        suraNumber: 105,
        suraAyahCount: 5),
    SuraDataModel(suraNameEN: "Quraish",
        suraNameAR: "قريش",
        suraNumber: 106,
        suraAyahCount: 4),
    SuraDataModel(suraNameEN: "Al-Ma'un",
        suraNameAR: "الماعون",
        suraNumber: 107,
        suraAyahCount: 7),
    SuraDataModel(suraNameEN: "Al-Kawthar",
        suraNameAR: "الكوثر",
        suraNumber: 108,
        suraAyahCount: 3),
    SuraDataModel(suraNameEN: "Al-Kafirun",
        suraNameAR: "الكافرون",
        suraNumber: 109,
        suraAyahCount: 6),
    SuraDataModel(suraNameEN: "An-Nasr",
        suraNameAR: "النصر",
        suraNumber: 110,
        suraAyahCount: 3),
    SuraDataModel(suraNameEN: "Al-Masad",
        suraNameAR: "المسد",
        suraNumber: 111,
        suraAyahCount: 5),
    SuraDataModel(suraNameEN: "Al-Ikhlas",
        suraNameAR: "الإخلاص",
        suraNumber: 112,
        suraAyahCount: 4),
    SuraDataModel(suraNameEN: "Al-Falaq",
        suraNameAR: "الفلق",
        suraNumber: 113,
        suraAyahCount: 5),
    SuraDataModel(suraNameEN: "An-Nas",
        suraNameAR: "الناس",
        suraNumber: 114,
        suraAyahCount: 6),

  ];

  List<SuraDataModel> recentlyReadSureList = [
    SuraDataModel(suraNameEN: "Al-Fatiha",
        suraNameAR: "الفاتحة",
        suraNumber: 1,
        suraAyahCount: 7),
    SuraDataModel(suraNameEN: "Al-Baqarah",
        suraNameAR: "البقرة",
        suraNumber: 2,
        suraAyahCount: 286),
    SuraDataModel(suraNameEN: "Aal-E-Imran",
        suraNameAR: "آل عمران",
        suraNumber: 3,
        suraAyahCount: 200),
    SuraDataModel(suraNameEN: "An-Nisa'",
        suraNameAR: "النساء",
        suraNumber: 4,
        suraAyahCount: 176),
    SuraDataModel(suraNameEN: "Al-Ma'idah",
        suraNameAR: "المائدة",
        suraNumber: 5,
        suraAyahCount: 120),
    SuraDataModel(suraNameEN: "Al-An'am",
        suraNameAR: "الأنعام",
        suraNumber: 6,
        suraAyahCount: 165),
  ];
  @override
  Widget build(BuildContext context) {
    var theme = Theme.of(context);
    return Container(
      height: double.infinity,
      width: double.infinity,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: AssetImage(AppAssets.quranBackground),
          fit: BoxFit.cover,
        ),
      ),
      child: SafeArea(
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              SizedBox(
                width: double.infinity,
                child: Image.asset(AppAssets.islamiLogo, fit: BoxFit.fitWidth),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(
                  horizontal: 20.0,
                  vertical: 10,
                ),
                child: TextFormField(
                  cursorColor: ColorPalette.primaryColor,
                  decoration: InputDecoration(
                    hintText: " Sura Name",
                    hintStyle: theme.textTheme.bodyLarge,
                    prefixIcon: Padding(
                      padding: const EdgeInsets.all(10.0),
                      child: ImageIcon(
                        AssetImage(AppAssets.quranIcon),
                        color: ColorPalette.primaryColor,
                      ),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(10),
                      borderSide: BorderSide(color: ColorPalette.primaryColor),
                    ),
                    enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(10),
                      borderSide: BorderSide(color: ColorPalette.primaryColor),
                    ),
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(
                    horizontal: 20.0, vertical: 10),
                child: Text(
                  "Most Recently",
                  style: theme.textTheme.bodyLarge,
                ),
              ),
              SizedBox(
                height: 170.0,
                child: ListView.separated(
                    scrollDirection: Axis.horizontal,
                    padding: EdgeInsets.symmetric(horizontal: 20),
                    itemBuilder: (context, index) {
                      return Recentlycardwidget(
                        suraDataModel: recentlyReadSureList[index],
                      );
                    },
                    separatorBuilder: (context, index) {
                      return SizedBox(width: 10.0);
                    },
                    itemCount: recentlyReadSureList.length),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(
                    horizontal: 20.0, vertical: 10),
                child: Text(
                  "Sures List",
                  style: theme.textTheme.bodyLarge,
                ),
              ),
              ListView.separated(
                  shrinkWrap: true,
                  physics: NeverScrollableScrollPhysics(),
                  padding: EdgeInsets.zero,
                  itemBuilder: (context, index) {
                    return QuranCardwidget(suraDataModel: allQuranSures[index]);
                  },
                  separatorBuilder: (context, index) {
                    return Divider(
                      color: Colors.white,
                      thickness: 2,
                      indent: 60,
                      endIndent: 60,
                    );
                  },
                  itemCount: allQuranSures.length),
            ],
          ),
        ),
      ),
    );
  }
}